name: Build.DockerImage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  version:
    name: "Version"
    runs-on: ubuntu-latest
    outputs:
      build_meta: ${{ steps.gitversion.outputs.buildMetaData }}
      build_semver: ${{ steps.gitversion.outputs.semVer }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
    - name: Get Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0

  build:
    name: "Build"
    needs: version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.0.5
    
    - name: Configure 1Password Service Account
      uses: 1password/load-secrets-action/configure@v1
      with:
        service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

    - name: Load secret
      id: load_secrets
      uses: 1password/load-secrets-action@v1
      env:
        DOCKER_LOGIN: op://cicd/docker_hub/username
        DOCKER_TOKEN: op://cicd/docker_hub/password
        COSIGN_PASSWORD: op://cicd/cosign_password/password
        
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
          username: ${{ env.DOCKER_LOGIN }}
          password: ${{ env.DOCKER_TOKEN }}
          
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and push
      id: build_push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8
        push: true
        tags: nlucansk/python-terraform-cdk:${{needs.version.outputs.build_semver}}-${{needs.version.outputs.build_meta}}
        
    - name: Sign image with a key
      run: |
        cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${TAGS}@${DIGEST}"
      env:
        TAGS: nlucansk/python-terraform-cdk:${{needs.version.outputs.build_semver}}-${{needs.version.outputs.build_meta}}
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        COSIGN_PASSWORD: ${{ env.COSIGN_PASSWORD }}
        DIGEST: ${{ steps.build_push.outputs.digest }}
