name: Build.DockerImage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  version:
    name: "Version"
    runs-on: ubuntu-latest
    outputs:
      build_meta: ${{ steps.gitversion.outputs.buildMetaData }}
      build_semver: ${{ steps.gitversion.outputs.semVer }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
    - name: Get Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0

  build:
    name: "Build"
    needs: version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
          echo ${{needs.version.outputs.build_meta}}
          echo ${{needs.version.outputs.build_semver}}
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag nlucansk/python-terraform-cdk:${{needs.version.outputs.build_semver}}-$GITHUB_REF_NAME-${{needs.version.outputs.build_meta}}
        docker tag nlucansk/python-terraform-cdk:${{needs.version.outputs.build_semver}}-$GITHUB_REF_NAME-${{needs.version.outputs.build_meta}} nlucansk/python-terraform-cdk:$GITHUB_REF_NAME
        docker push nlucansk/python-terraform-cdk:$GITHUB_REF_NAME
        docker push nlucansk/python-terraform-cdk:${{needs.version.outputs.build_semver}}-$GITHUB_REF_NAME-${{needs.version.outputs.build_meta}}
