name: Build.DockerImage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  version:
    name: "Version"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
    - name: Get Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0
    - name: Display GitVersion outputs (step output)
      run: |
        echo "build_meta=${{ steps.gitversion.outputs.buildMetaData }}" >> $GITHUB_OUTPUT
        echo "build_semver=${{ steps.gitversion.outputs.semVer }}" >> $GITHUB_OUTPUT

  build:
    name: "Build"
    needs: version
    runs-on: [self-hosted, linux, docker]
    steps:
    - name: Build the Docker image
      shell: bash -leo pipefail {0}
      run: |
          echo ${{needs.version.outputs.build_meta}}
          echo ${{needs.version.outputs.build_semver}}
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag nlucansk/python-terraform-cdk:$GITHUB_REF_NAME-$GITHUB_RUN_NUMBER
        docker tag nlucansk/python-terraform-cdk:$GITHUB_REF_NAME-$GITHUB_RUN_NUMBER nlucansk/python-terraform-cdk:$GITHUB_REF_NAME
        docker push nlucansk/python-terraform-cdk:$GITHUB_REF_NAME
        docker push nlucansk/python-terraform-cdk:$GITHUB_REF_NAME-$GITHUB_RUN_NUMBER
