name: Build.DockerImage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Version:
    runs-on: [self-hosted, linux, docker]
    container: node:14.16
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
  Build:
    - name: Build the Docker image
      shell: bash -leo pipefail {0}
      run: |
          echo ${{ steps.version.outputs.version }}
          source $HOME/variables.sh
          echo "docker_username=$DOCKER_USERNAME" >> $GITHUB_ENV
          echo "docker_pat=$DOCKER_PAT" >> $GITHUB_ENV
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ env.docker_username }}
        password: ${{ env.docker_pat }}
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag nlucansk/python-terraform-cdk:$GITHUB_REF_NAME-$GITHUB_RUN_NUMBER
        docker tag nlucansk/python-terraform-cdk:$GITHUB_REF_NAME-$GITHUB_RUN_NUMBER nlucansk/python-terraform-cdk:$GITHUB_REF_NAME
        docker push nlucansk/python-terraform-cdk:$GITHUB_REF_NAME
        docker push nlucansk/python-terraform-cdk:$GITHUB_REF_NAME-$GITHUB_RUN_NUMBER
